# Generated by Django 4.2.1 on 2023-05-08 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('forklifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='useracc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autocar',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.carmodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='autocar',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='autocar',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='autocar',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='autocar',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='autocar',
            name='steerable_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.steerableaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='autocar',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
