# Generated by Django 4.2.1 on 2023-05-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forklifts', '0003_alter_autocar_serial_number'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failurenode',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'verbose_name': 'Вид технического обслуживания', 'verbose_name_plural': 'Виды технического обслуживания'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='autocar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.autocar', verbose_name='Заводской номер погрузчика'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='autocar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklifts.autocar', verbose_name='Заводской номер погрузчика'),
        ),
    ]
